#!/usr/bin/env python3
# -*- coding: utf-8 -*-

__author__ = 'CYX'

import aiohttp, asyncio
import json, time
import xlrd

COLUM_FAMILY = ['name', 'label', 'db_affiliation', 'eissn', 'pissn', 'unified_id', 'url', 'lib_url', 'type', 'language', 'access_mode', 'discipline_classified', 'status', 'journal_created', 'keywords', 'sponsor', 'editor_affiliation', 'nationality']


#DB_HOST = '1.85.37.132'
DB_HOST = 'localhost'

async def journal_data(client, data, headers):
	r = await client.post('http://'+DB_HOST+'/api/journal/items', data=json.dumps(data), headers = headers)
	await r.release()

workbook = xlrd.open_workbook(r'journal_1.xlsx')

sheet1_name = workbook.sheet_names()[0]
print(sheet1_name)

sheet1 = workbook.sheet_by_name(sheet1_name)
print(sheet1.name, sheet1.nrows, sheet1.ncols)

items = []
for i in range(sheet1.nrows):
	if i == 0:
		continue
	rows = sheet1.row_values(i)
	item = {}
	for j in range(len(COLUM_FAMILY)):
		column_name = COLUM_FAMILY[j]
		item[column_name] = sheet1.cell(i,j).value

	items.append(item)

data = {'items':items}
headers = {'content-type': 'application/json'}

with aiohttp.ClientSession() as client:
	tasks = [journal_data(client, data, headers)]

	asyncio.get_event_loop().run_until_complete(asyncio.wait(tasks))
